services:
  api:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    environment:
      - PYTHONUNBUFFERED=1
  ui:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports: ["5173:5173"]
    depends_on: [api]